spring:
  cloud:
    gateway:
      routes:
        - id: api_service
          uri: http://localhost:8081
          filters:
            - AddResponseHeader=Location, /api/v1.1/service/{segment}
            - SetStatus=302
          predicates:
            - Path=/api/service/{segment}
        - id: v1
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/service/**
          filters:
            - RewritePath=/api/v1/service/(?<segment>.*), /api/service/$\{segment}
        - id: v1.1
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1.1/service/**
          filters:
            - RewritePath=/api/v1.1/service/(?<segment>.*), /api/service/$\{segment}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"